name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build the mod
        run: ./gradlew :build --no-daemon --stacktrace

      - name: Publish mod
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: JW3bGnLO
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 409222
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: build/libs/!(*-@(dev|sources)).jar

          name: 0.3.7 for MC 1.19.4
          version: 0.3.7+1.19.4
          version-type: release

          loaders: |
            fabric

          game-versions: |
            1.19.4

          dependencies: |
            fabric-api    | depends
            cloth-config  | depends
            modmenu       | recommends
