name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build 1.18 project
        run: ./gradlew :microdurability-1.18:build --no-daemon --stacktrace

      - name: Build 1.19 project
        run: ./gradlew :microdurability-1.19:build --no-daemon --stacktrace

      # - name: Upload GitHub release
      #   uses: AButler/upload-release-assets@v2.0
      #   with:
      #     files: "**/build/libs/*.jar;!**/build/libs/*-sources.jar;!**/build/libs/*-dev.jar;!bettersleeping-core/"
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish 1.18 version
        uses: Kir-Antipov/mc-publish@v2.0
        with:
          # modrinth-id: /
          # modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 409222
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: microdurability-1.18/build/libs/!(*-@(dev|sources)).jar

          name: microDurability 0.3.3 for 1.18
          version: 0.3.3+1.18
          version-type: release

          loaders: |
            fabric

          game-versions: |
            1.18
            1.18.1
            1.18.2

      - name: Publish 1.19 version
        uses: Kir-Antipov/mc-publish@v2.0
        with:
          # modrinth-id: /
          # modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 409222
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: microdurability-1.19/build/libs/!(*-@(dev|sources)).jar

          name: microDurability 0.3.3 for 1.19
          version: 0.3.3+1.19
          version-type: beta

          loaders: |
            fabric

          game-versions: |
            22w19a
